#publish_mode: editorial_workflow

backend:
  name: github
  branch: main
  repo: altinn/altinn-infoportal
  #open_authoring: true 

local_backend: true

i18n:
  structure: multiple_files
  locales: [nb,en]
  default_locale: nb

media_folder: static/img
public_folder: /img
collections:
  - name: 'nyheter'
    publish: true # false hides publishing controls
    i18n: true
    create: true
    label: 'Nyheter'
    folder: 'content/nyheter'
    path: '{{slug}}/index'
    filter: {field: "cmsedit", value: true}
    media_folder: ''
    public_folder: ''
    editor:
      preview: false
    fields:
      - { label: 'Tittel', name: 'title', widget: 'string', i18n: true, required: true }
      - { label: 'Url', name: 'url', widget: 'string', i18n: true, hint: "NB! ingen ÆØÅ e.g: /nb/forste-artikkel", required: false }
      - { label: 'SEO', name: 'seo-description', widget: 'string', i18n: true, hint: "Meta - description", required: false }
      - { label: 'Ingress', name: 'description', widget: 'text', i18n: true, required: true }
      - { label: 'Vis innholdsfortegnelse', name: 'toc', widget: boolean, i18n: true }
      - { label: 'Innhold', name: 'body', widget: 'markdown', i18n: true, required: true}
      # HIDDEN FIELDS
      - { label: 'Last Mod', name: 'lastmod', widget: 'hidden', i18n: true }
      - { label: 'Allow CMS Edit', name: 'cmsedit', widget: 'hidden', i18n: true, default: true }

  - name: 'om-altinn'
    publish: true # false hides publishing controls
    i18n: true
    create: true
    label: 'Om altinn'
    folder: 'content/om-altinn'
    path: '{{slug}}/index'
    filter: {field: "cmsedit", value: true}
    media_folder: ''
    public_folder: ''
    editor:
      preview: false
    fields:
      - { label: 'Tittel', name: 'title', widget: 'string', i18n: true }
      - { label: 'Lenke Tittel', name: 'linktitle', widget: 'string', i18n: true, hint: Tittel for lenke til innhold }
      - { label: 'Url', name: 'url', widget: 'string', i18n: true, hint: "NB! ingen ÆØÅ e.g: /nb/forste-artikkel", required: false }
      - { label: 'SEO', name: 'seo-description', widget: 'string', i18n: true, hint: "Meta - description", required: false }
      - { label: 'Ingress', name: 'description', widget: 'text', i18n: true }
      - { label: 'Prioritering', name: 'weight', widget: 'number', i18n: true, hint: 'Prioritering på utlistning' }
      - { label: 'Vis innholdsfortegnelse', name: 'toc', widget: boolean, i18n: true }
      - { label: 'Vis "Fant du de du lette etter?"', name: 'didyoufind', widget: boolean, i18n: true }
      - { label: 'Innhold', name: 'body', widget: 'markdown', i18n: true }
      # HIDDEN FIELDS
      - { label: 'Last Mod', name: 'lastmod', widget: 'hidden', i18n: true }
      - { label: 'Allow CMS Edit', name: 'cmsedit', widget: 'hidden', i18n: true, default: true }

