#publish_mode: editorial_workflow

backend:
  name: github
  branch: main
  repo: altinn/altinn-infoportal
  #open_authoring: true 

local_backend: true

i18n:
  structure: multiple_files
  locales: [nb,en]
  default_locale: nb

media_folder: static/img
public_folder: /img
collections:
  - name: 'nyheter'
    publish: false # hides publishing controls
    i18n: true
    create: true
    label: 'Nyheter'
    folder: 'content/nyheter'
    path: '{{slug}}/index'
    filter: {field: "cmsedit", value: true}
    media_folder: ''
    public_folder: ''
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true, required: true }
      - { label: 'Last Mod', name: 'lastmod', widget: 'hidden', i18n: true }
      - { label: 'Allow CMS Edit', name: 'cmsedit', widget: 'hidden', i18n: true, default: true }
      - { label: 'Description', name: 'description', widget: 'text', i18n: true, required: true }
      - { label: 'Show Table of Content', name: 'toc', widget: boolean, i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true, required: true}

  - name: 'om-altinn'
    publish: false # hides publishing controls
    i18n: true
    create: true
    label: 'Om altinn'
    folder: 'content/om-altinn'
    path: '{{slug}}/index'
    filter: {field: "cmsedit", value: true}
    media_folder: ''
    public_folder: ''
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Link Title', name: 'linktitle', widget: 'string', i18n: true }
      #- { label: 'Url', name: 'url', widget: 'string', i18n: true }
      - { label: 'Last Mod', name: 'lastmod', widget: 'hidden', i18n: true }
      - { label: 'Allow CMS Edit', name: 'cmsedit', widget: 'hidden', i18n: true, default: true }
      - { label: 'Description', name: 'description', widget: 'text', i18n: true }
      - { label: 'Weight', name: 'weight', widget: 'number', i18n: true }
      - { label: 'Show Table of Content', name: 'toc', widget: boolean, i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }