#publish_mode: editorial_workflow

backend:
  name: github
  branch: main
  repo: altinn/altinn-infoportal
  #open_authoring: true 

local_backend: true

i18n:
  structure: multiple_files
  locales: [nb,en]
  default_locale: nb

media_folder: static/img
public_folder: /img
collections:


# HJELP
  - name: 'help'
    publish: true # false hides publishing controls
    i18n: true
    create: true
    label: 'Hjelp'
    folder: 'content/hjelp'
    path: '{{slug}}/index'

    media_folder: ''
    public_folder: ''
    editor:
      preview: false
    nested:
      depth: 100
      summary: '{{title}}'
    fields:
      - { label: 'Tittel', name: 'title', widget: 'string', i18n: true, required: true }
      - { label: 'Url', name: 'url', widget: 'string', i18n: true, hint: "NB! ingen ÆØÅ e.g: /nb/forste-artikkel", required: false }
      - { label: 'SEO', name: 'seo-description', widget: 'string', i18n: true, hint: "Meta - description", required: false }
      #- { label: 'Prioritering', name: 'weight', widget: 'number', i18n: true, hint: 'Prioritering på utlistning', required: false }
      - { label: 'Ingress', name: 'description', widget: 'text', i18n: true, required: true }
      - { label: 'Vis "Står du fast?"', name: 'show_ays', widget: boolean, default: false, i18n: true, required: false, hint: 'Vises på slutten av innholdet' }
      - { label: 'Innhold', name: 'body', widget: 'markdown', i18n: true, required: false}
      # HIDDEN FIELDS
      - { label: 'Allow CMS Edit', name: 'cmsedit', widget: 'hidden', i18n: true, default: true }
    meta: { path: { widget: string, label: 'Path', index_file: '_index' } }

# NYHETER
  - name: 'nyheter'
    publish: true # false hides publishing controls
    i18n: true
    create: true
    label: 'Nyheter'
    folder: 'content/nyheter'
    path: '{{slug}}/index'
    filter: {field: "cmsedit", value: true}
    media_folder: ''
    public_folder: ''
    editor:
      preview: false
    fields:
      - { label: 'Tittel', name: 'title', widget: 'string', i18n: true, required: true }
      - { label: 'Url', name: 'url', widget: 'string', i18n: true, hint: "NB! ingen ÆØÅ e.g: /nb/forste-artikkel", required: false }
      - { label: 'SEO', name: 'seo-description', widget: 'string', i18n: true, hint: "Meta - description", required: false }
      - { label: 'Sist endret dato', name: 'lastmod', widget: 'date', i18n: true, format: "YYYY-MM-DD" }
      - { label: 'Ingress', name: 'description', widget: 'text', i18n: true, required: true }
      - { label: 'Vis innholdsfortegnelse', name: 'toc', widget: boolean, i18n: true, required: false }
      - { label: 'Innhold', name: 'body', widget: 'markdown', i18n: true, required: true}
      # HIDDEN FIELDS
      - { label: 'Allow CMS Edit', name: 'cmsedit', widget: 'hidden', i18n: true, default: true }

  # OM ALTINN
  - name: 'om-altinn'
    publish: true # false hides publishing controls
    i18n: true
    create: true
    label: 'Om altinn'
    folder: 'content/om-altinn'
    path: '{{slug}}/index'
    filter: {field: "cmsedit", value: true}
    media_folder: ''
    public_folder: ''
    editor:
      preview: false
    fields:
      - { label: 'Tittel', name: 'title', widget: 'string', i18n: true }
      - { label: 'Lenke Tittel', name: 'linktitle', widget: 'string', i18n: true, hint: Tittel for lenke til innhold }
      - { label: 'Url', name: 'url', widget: 'string', i18n: true, hint: "NB! ingen ÆØÅ e.g: /nb/forste-artikkel", required: false }
      - { label: 'SEO', name: 'seo-description', widget: 'string', i18n: true, hint: "Meta - description", required: false }
      - { label: 'Sist endret dato', name: 'lastmod', widget: 'date', i18n: true, format: "YYYY-MM-DD" }
      - { label: 'Ingress', name: 'description', widget: 'text', i18n: true }
      - { label: 'Prioritering', name: 'weight', widget: 'number', i18n: true, hint: 'Prioritering på utlistning' }
      - { label: 'Vis innholdsfortegnelse', name: 'toc', widget: boolean, i18n: true, required: false }
      - { label: 'Vis "Fant du de du lette etter?"', name: 'didyoufind', widget: boolean, i18n: true,required: false }
      - { label: 'Innhold', name: 'body', widget: 'markdown', i18n: true }
      # HIDDEN FIELDS
      - { label: 'Allow CMS Edit', name: 'cmsedit', widget: 'hidden', i18n: true, default: true }

  # TEKSTBLOKKER
  - name: 'textblocks'
    i18n: true
    label: 'Tekstblokker'
    folder: 'content/textblocks'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    view_filters:
      - label: tblocks for - hjelp
        field: category
        pattern: 'HJELP'
      - label: tblocks for - nyheter
        field: category
        pattern: 'NYHETER'
      - label: tblocks for - starte og drive
        field: category
        pattern: 'STARTE OG DRIVE'
    fields:
      - { label: UUID, name: uuid, widget: uuid, i18n: duplicate }
      - 
        label: "Kategorier"
        name: "category"
        widget: "select"
        options: ["NYHETER", "HJELP", "STARTE OG DRIVE"]
        multiple: true
        i18n: duplicate
      - { label: 'Navn på blokk', name: 'title', widget: 'string', i18n: duplicate }
      - { label: 'Innhold', name: 'body', widget: 'markdown', i18n: true}